version: '3'
services:

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    network_mode: bridge
  
  browser:
    container_name: filebrowser
    restart: unless-stopped
    depends_on:
      - nginx-proxy-manager
    volumes:
      - '/root:/srv'
      - './filebrowser/data:/data'
      #- './filebrowser/filebrowser.db:/database.db'
      #- './filebrowser/.filebrowser.json:/.filebrowser.json'
    image: filebrowser/filebrowser
    network_mode: bridge

  v2fly-core:
    container_name: v2fly
    depends_on:
      - browser
      - nginx-proxy-manager
    volumes:
      - './v2fly:/etc/v2ray'
    restart: unless-stopped
    image: v2fly/v2fly-core:v4.45.2
    network_mode: bridge


#   portainer-ce:
#     image: 'portainer/portainer-ce'
#     container_name: portainer
#     privileged: true
#     depends_on:
#       - browser
#     volumes:
#       - ./portainer/data:/data
#       - /var/run/docker.sock:/var/run/docker.sock
#     restart: unless-stopped
#     networks:
#       - default
  
#   monitor:
#     image: antonyleons/ward
#     restart: unless-stopped
#     container_name: ward
#     depends_on:
#       - portainer-ce
#     #ports:
#       #- '4000:4000'
#     environment:
#       - WARD_PORT=4000
#       - WARD_THEME=light
#       - WARD_NAME=server-monitor
#     privileged: true

